services:
  db:
    image: mysql:8.0
    container_name: "AD_DB"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s
  
  web:
    build: .
    container_name: "AD_WEB"
    restart: on-failure:3
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${db}
      - DATABASE_USER=${AD_admin}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/staticfiles
    ports:
      - "8003:8003" 

volumes:
  mysql_data: