services:
  db:
    image: mysql:8.0
    container_name: active_directory
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


  web:
    build: .
    container_name: active_directory_web
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - DATABASE_HOST= ${DB_HOST}
      - DATABASE_USER= ${DB_USER}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure:3

volumes:
  mysql_data: