services:
  db:
    image: mysql:8.0
    container_name: "evs_db_dev"
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s

  web:
    build: .
    container_name: "evs_web_dev"
    entrypoint: ["sh", "/app/entrypoint.sh"]
    env_file:
      - .env
    restart: on-failure:3
    volumes:
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
      - ./static:/app/static
    ports:
      - "8001:8001"

    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DJANGO_SETTINGS_MODULE: XUOSA_EVS.settings 

volumes:
  mysql_data:

  