version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # uses the one we updated with python:3.12
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_NAME=projectdb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 012790
      MYSQL_DATABASE: projectdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 012790
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_data:
