# Generated by Django 5.1.7 on 2025-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='year_level',
            field=models.CharField(max_length=10),
        ),
    ]
