# Generated by Django 5.1.7 on 2025-04-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('acad_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('year_start', models.DateField()),
                ('year_end', models.DateField()),
                ('semester', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('violation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uniform_violation', models.BooleanField(default=0)),
                ('dress_code_violation', models.BooleanField(default=0)),
                ('id_violation', models.BooleanField(default=0)),
                ('id_not_claimed_violation', models.BooleanField(default=0)),
                ('ssio_id', models.IntegerField()),
                ('id_status', models.IntegerField(default=0)),
                ('ticket_status', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_validated', models.DateTimeField(blank=True, null=True)),
                ('acad_year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TS.student')),
            ],
        ),
    ]
